server:
  port: 30000
spring:
  redis:
    # redis 服务器地址
    ip: 8.131.69.238
    # Redis 服务器端连接端口
    port: 6379
    # redis 服务器连接密码
    password: Jovision123$
    # 连接超时时间（毫秒）
    timeout: 1000
    # 连接池最大连接数
    maxactive: 200
    # 连接池最大阻塞等待时间（使用负值表示没有）
    maxwait: 1
    # 连接池中的最大空闲连接
    maxidle: 10
  route:
    wisdom:
      id: wisdom_route
      url: http://localhost:20001
      intercept: /api/wisdom/**